
jobs:
- job: SourcePkg
  pool:
    vmImage: ubuntu-16.04
  
  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH

  - script: conda create -n build -qy python=3.7
    displayName: Create Conda env

  - script: |
      source activate build
      python setup.py sdist -d $(Build.ArtifactStagingDirectory)
    displayName: Build sdist

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'source'

- job: LinuxPkg
  dependsOn: [SourcePkg, LinuxConda]
  pool:
    vmImage: ubuntu-16.04
  
  steps:
  - bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
    displayName: Add conda to PATH

  - script: conda create -n build -qy python=3.7 conda-build anaconda-client
    displayName: Create Conda env

  - script: |
      source activate build
      conda build --output-folder $(Build.ArtifactStagingDirectory) conda
    displayName: Build Conda packages

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'conda'

- job: WinPkg
  dependsOn: [SourcePkg, WindowsConda]
  pool:
    vmImage: vs2017-win2016

  steps:
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH
  
  - script: conda create -n build -qy python=3.7 conda-build anaconda-client
    displayName: Create Conda env

  - script: |
      call activate build
      conda build --output-folder $(Build.ArtifactStagingDirectory) conda
    displayName: Build Conda packages

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'conda'

- job: MacPkg
  dependsOn: [SourcePkg, MacConda]
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda create -n build -qy python=3.7 conda-build anaconda-client
    displayName: Create Conda env

  - script: |
      source activate build
      conda build --output-folder $(Build.ArtifactStagingDirectory) conda
    displayName: Build Conda packages
  
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'conda'
