jobs:
- job: 'LinuxSketchyDeps'
  pool:
    vmImage: ubuntu-16.04

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip
      pip install $(pip.deps)
    displayName: 'Install dependencies'
  
  - script: |
      python -m pip install cffi
    displayName: 'Install partial extra deps'
    
  - script: |
      mkdir -p build
      python3 -m pytest --junitxml=build/test-results.xml --cov=lenskit
    displayName: 'pytest'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'build/test-results.xml'
      testRunTitle: 'Publish test results for Python $(python.version)'
  
  - template: ./nix-coverage.yml
