{% set data = load_setup_py_data() %}

package:
  name: lenskit
  {% if GIT_DESCRIBE_NUMBER > '0' %}
  version: {{data.get('version')}}.dev{{GIT_DESCRIBE_NUMBER}}+{{GIT_DESCRIBE_HASH}}
  {% else %}
  version: {{data.get('version')}}
  {% endif %}

source:
  path: ../

requirements:
  build:
  host:
    - python {{ python }}
    - setuptools
    - pytest-runner
    - numba >=0.40
    - pandas
    - numpy
    - scipy
    - pyarrow
    - python-snappy
    - cffi
  run:
    - python
    - pandas
    - scipy
    - numba >=0.40
    - pyarrow
    - fastparquet
    - python-snappy
    - cffi

test:
  source_files:
    - tests
    - tests/*.py
    - tests/*.csv
    - ml-latest-small
    - ml-latest-small/*.csv
  requires:
    - pytest
    - pytest-arraydiff
  commands:
    - pytest tests -m "not slow"
